import type { NextPage } from 'next'
import Head from 'next/head'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>ホーム/Twitter</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='text-white'>
        <h1 className="text-3xl font-bold">
          twitter home
        </h1>
      </main>
    </div>
  )
}

export default Home
