import type { NextPage } from 'next'
import Head from 'next/head'
import Center from '../components/center'


const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>ホーム/Twitter</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='text-white'>
        <Center></Center>
      </main>
    </div>
  )
}

export default Home
